Add tensorflow module
terraform-alicloud-modules/terraform-alicloud-tensorflow pull request #1
Opened 2020-02-17 12:44 UTC by Rich-yi

2020-02-17 13:06 UTC, zql-tqy commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
.idea 没有忽略吧

2020-02-17 13:06 UTC, zql-tqy commented on README-CN.md
> +  instance_type = "ecs.n4.small"
fmt

2020-02-17 13:06 UTC, zql-tqy commented on README.md
> +* One of `vswitch_id` or `vswitch_ids` is required. If both are provided, the value of `vswitch_id` is prepended to the value of `vswitch_ids`.
这段在中文中没有吧

2020-02-17 13:06 UTC, zql-tqy commented on variables.tf
> +  type        = number
把default值在描述中写一下吧

2020-02-17 13:06 UTC, zql-tqy commented on variables.tf
> +  default     = ""
没有type

2020-02-17 13:06 UTC, zql-tqy commented on variables.tf
> +  default     = ""
type

2020-02-19 08:09 UTC, xiaozhu36 requested changes

2020-02-19 08:09 UTC, xiaozhu36 commented on variables.tf
> +variable "ecs_instance_name" {
只有ecs这一个资源，不需要ecs_这个前缀了

2020-02-19 08:09 UTC, xiaozhu36 commented on outputs.tf
> +output "this_ecs_vswitch_id" {
去掉ecs，只有一个resource

2020-02-19 08:09 UTC, xiaozhu36 commented on main.tf
> +  name_regex  = "ubuntu_16"
ubuntu 18

2020-02-19 08:09 UTC, xiaozhu36 commented on install-on-ecs.sh
> +#!/bin/sh
改成 install.sh

2020-02-19 08:09 UTC, xiaozhu36 commented on README.md
> +  source  = "alibaba/tensorflow/alicloud"
这个地址不对

2020-02-19 08:09 UTC, xiaozhu36 commented on README-CN.md
> +本 Terraform 模块将基于阿里云 ECS 实例来部署的 Tensorflow。
多一个 “的” 吧

2020-02-19 09:06 UTC, xiaozhu36 requested changes

2020-02-19 09:06 UTC, xiaozhu36 commented on README-CN.md
> +  image_id                    = data.alicloud_images.ubuntu.ids.0
这个地方不要用 datasource

2020-02-19 09:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "The image id used to launch one ecs instance. It only support CentOS_7."
这个描述不对，要说清楚，如果不指定，将通过data来获取

2020-02-19 09:06 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
这个给一个默认值 cloud_ssd

2020-02-19 09:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "A list of security group ids to associate with ECS and RDS Mysql Instance."
这个也是有问题的，为什么每次都会有这些问题

2020-02-21 01:07 UTC, xiaozhu36 requested changes

2020-02-21 01:07 UTC, xiaozhu36 commented on README-CN.md
> +  image_id                    = "ubuntu_18_04_x64_20G_alibase_xxxxxx.vhd"
imageid没必要脱敏

2020-02-21 01:07 UTC, xiaozhu36 commented on outputs.tf
> +output "this_instance_id" {
在多输出一些实例的参数吧

2020-02-21 01:07 UTC, xiaozhu36 commented on variables.tf
> +  default     = ""
这个在这个场景中可以给一个默认值 ecs.sn1ne.large

2020-02-21 03:16 UTC, xiaozhu36 requested changes

2020-02-21 03:16 UTC, xiaozhu36 commented on outputs.tf
> +  value       = module.ecs-instance.this_instance_id[0]
module.ecs-instance.this_instance_id[0] 这个有可能是空的，所以用 concat来获取；另外其他的参数也是一样的，因为你用的是ecs-instance module，所以这个其他的参数返回的也是一个list，你需要取第一个

2020-02-21 03:16 UTC, xiaozhu36 commented on README-CN.md
> +  instance_name               = "myTensorflow1"
这个地方加一个region

2020-02-21 05:18 UTC, xiaozhu36 approved these changes

2020-02-21 05:18 UTC, merged